version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    container_name: rag-frontend
    ports:
      - "3000:3000" # host port : container port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: rag-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads:/app/uploads
    env_file:
      - ./backend/.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  pdf-worker:
    build: ./backend
    container_name: rag-pdf-worker
    command: npm run worker:pdf

    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads:/app/uploads

    env_file:
      - ./backend/.env

    depends_on:
      redis:
        condition: service_healthy

  chunk-worker:
    build: ./backend
    container_name: rag-pdf-worker_chunking
    command: npm run worker:pdf_chunk

    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env

    depends_on:
      redis:
        condition: service_healthy
      # - ollama

  mongodb:
    image: mongo:8
    container_name: rag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: rag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-ui
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama

volumes:
  mongodb_data:
  redis_data:
  uploads:
  # ollama_data: